replicaCount: 3

image:
  repository: eranlebovic/frontend-ui
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  loadBalancerClass: "tailscale"
  annotations:
    tailscale.com/hostname: "devops-frontend"
