replicaCount: 3

image:
  repository: eranlebovic/frontend-ui
  pullPolicy: Always
  tag: "v13"

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  loadBalancerClass: "tailscale"
  annotations:
    tailscale.com/hostname: "devops-frontend"
