replicaCount: 3

image:
  repository: eranlebovic/frontend-ui
  pullPolicy: Always
  tag: "v-broken-demo"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  loadBalancerClass: "tailscale"

rollout:
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: {duration: 10s}
        - setWeight: 50
        - pause: {duration: 10s}
