replicaCount: 3

image:
  repository: eranlebovic/backend-api
  pullPolicy: Always
  tag: "v43" # This tag will be overridden by Jenkins/GitOps

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000
  loadBalancerClass: "tailscale"

redis:
  host: redis-service
  port: 6379

rollout:
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
        - setWeight: 50
        - pause: {}
