replicaCount: 3

image:
  repository: eranlebovic/backend-api
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000
  loadBalancerClass: "tailscale"

redis:
  host: redis-service
  port: 6379
