apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: default
  labels:
    app: backend-api
spec:
  # 1. High Availability: We want 2 copies running at all times
  replicas: 3
  
  # 2. Selector: How K8s knows which pods belong to this deployment
  selector:
    matchLabels:
      app: backend-api
      
  # 3. Pod Template: The blueprint for the containers
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: eranlebovic/backend-api:v10
        imagePullPolicy: Always                  # <--- Good for dev
        ports:
        - containerPort: 5000
        
        # --- NEW: ENV VAR INJECTION ---
        env:
        - name: REDIS_HOST
          value: "redis-service"  # <--- K8s Service Name (Service Discovery!)
        
        - name: REDIS_PORT
          value: "6379"
          
        - name: REDIS_PASSWORD    # <--- The Secret Injection again
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: redis-password
              
        # Keep your probes...
        livenessProbe:
           # ... (same as before)
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
