apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: default
spec:
  # 1. Selector: connects this Service to your Deployment
  selector:
    app: backend-api
  
  # 2. Type: NodePort (Opens a specific port on EVERY worker node)
  # Best Practice: In Prod, we use 'ClusterIP' + Ingress. 
  # For this specific testing stage, NodePort is the quickest way to verify access.
  type: NodePort
  
  ports:
    - protocol: TCP
      port: 80          # The port the Service listens on internally
      targetPort: 5000  # The port your Python Container listens on
      nodePort: 30001   # The fixed port on your Worker Nodes (30000-32767)
